### ISSUE TITLE
How do I set ORDER BY time or  id

### ISSUE THREAD

**Issue by eArabic** [sayopaul/paginationclass#1]
Thank you very much for this file sharing.
How can I arrange items displayed by time or  id
How do I set ORDER BY  time or  id
I want to be on top of the latest at the beginning of page
Sorry for the mistakes I do not know English, and thank you very much.

![0102](https://cloud.githubusercontent.com/assets/24383546/21427113/a8770b3e-c863-11e6-86ab-ce82ae3769ad.png)

**Comment by sayopaul** [comment]
@eArabic Hello there. To ORDER by the time or ID, all you have to do is edit the SQL query a bit. 
To do this, go to the paginate() method. It is at line 110. At line 116, you should see a
 `$sql= " SELECT * FROM " . $this->database_table_name . " LIMIT " . $this->limit_per_page . " OFFSET ". $offset ;` .
 Now all we need to do is add the ORDER BY to the sql query. Here is an example. You have to notice that when using ORDER BY you can choose to add ASC or DESC depending on how you want it to be arranged. SInce you want the latest to be at the top of the page, you would use DESC . Here is the code for that 

`$sql= " SELECT * FROM " . $this->database_table_name. " ORDER BY customerNumber DESC " . " LIMIT " . $this->limit_per_page . " OFFSET ". $offset ;`

Hence, you would replace line 116 with this line below


**`$sql= " SELECT * FROM " . $this->database_table_name. " ORDER BY time DESC " . " LIMIT " . $this->limit_per_page . " OFFSET ". $offset ;`**
                                                     OR
**`$sql= " SELECT * FROM " . $this->database_table_name. " ORDER BY id DESC " . " LIMIT " . $this->limit_per_page . " OFFSET ". $offset ;`**



I have attached a new class after making the necessary changes for you. Goodluck ! :) and please give a **STAR** 
[eArabic.zip](https://github.com/sayopaul/paginationclass/files/670030/eArabic.zip)

**Comment by eArabic** [comment]
Thank you very much, now works very excellent

Special greetings to you and thanks
